// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-ooIDK6jo4y9ZmSCIn0hjq_XxOx33eY',
    appId: '1:123538371960:web:54c92a1c850643c055848d',
    messagingSenderId: '123538371960',
    projectId: 'facebookproj-1e289',
    authDomain: 'facebookproj-1e289.firebaseapp.com',
    storageBucket: 'facebookproj-1e289.firebasestorage.app',
    measurementId: 'G-Q4M8MX75KQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3ZH8YIXGVdA22S4ksl4MRBt3n3lZvj4',
    appId: '1:123538371960:ios:1c0bb0c2018f366155848d',
    messagingSenderId: '123538371960',
    projectId: 'facebookproj-1e289',
    storageBucket: 'facebookproj-1e289.firebasestorage.app',
    iosClientId: '123538371960-7lccd6t7oqqnqjuq1fqvejgeqmqvlbb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu3ZH8YIXGVdA22S4ksl4MRBt3n3lZvj4',
    appId: '1:123538371960:ios:1c0bb0c2018f366155848d',
    messagingSenderId: '123538371960',
    projectId: 'facebookproj-1e289',
    storageBucket: 'facebookproj-1e289.firebasestorage.app',
    iosClientId: '123538371960-7lccd6t7oqqnqjuq1fqvejgeqmqvlbb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV-ooIDK6jo4y9ZmSCIn0hjq_XxOx33eY',
    appId: '1:123538371960:web:b576e26e5cf15a1c55848d',
    messagingSenderId: '123538371960',
    projectId: 'facebookproj-1e289',
    authDomain: 'facebookproj-1e289.firebaseapp.com',
    storageBucket: 'facebookproj-1e289.firebasestorage.app',
    measurementId: 'G-BEGEWQKFBB',
  );

}